package HibernatePackage;
// Generated 16/Abr/2014 23:30:37 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conferenciacomiteartigo generated by hbm2java
 */
public class Conferenciacomiteartigo  implements java.io.Serializable {


     private Integer id;
     private Conferenciacomite conferenciacomite;
     private Artigo artigo;
     private String estado;
     private Date dataInicioLicitacao;
     private Date dataFimLicitacao;
     private Byte pontuacao;
     private Byte pontuacaoComite;
     private Set<Artigorevisao> artigorevisaos = new HashSet<Artigorevisao>(0);
     private Set<Conferenciacomiteartigoforum> conferenciacomiteartigoforums = new HashSet<Conferenciacomiteartigoforum>(0);

    public Conferenciacomiteartigo() {
    }

	
    public Conferenciacomiteartigo(Conferenciacomite conferenciacomite, Artigo artigo) {
        this.conferenciacomite = conferenciacomite;
        this.artigo = artigo;
    }
    public Conferenciacomiteartigo(Conferenciacomite conferenciacomite, Artigo artigo, String estado, Date dataInicioLicitacao, Date dataFimLicitacao, Byte pontuacao, Byte pontuacaoComite, Set<Artigorevisao> artigorevisaos, Set<Conferenciacomiteartigoforum> conferenciacomiteartigoforums) {
       this.conferenciacomite = conferenciacomite;
       this.artigo = artigo;
       this.estado = estado;
       this.dataInicioLicitacao = dataInicioLicitacao;
       this.dataFimLicitacao = dataFimLicitacao;
       this.pontuacao = pontuacao;
       this.pontuacaoComite = pontuacaoComite;
       this.artigorevisaos = artigorevisaos;
       this.conferenciacomiteartigoforums = conferenciacomiteartigoforums;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conferenciacomite getConferenciacomite() {
        return this.conferenciacomite;
    }
    
    public void setConferenciacomite(Conferenciacomite conferenciacomite) {
        this.conferenciacomite = conferenciacomite;
    }
    public Artigo getArtigo() {
        return this.artigo;
    }
    
    public void setArtigo(Artigo artigo) {
        this.artigo = artigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getDataInicioLicitacao() {
        return this.dataInicioLicitacao;
    }
    
    public void setDataInicioLicitacao(Date dataInicioLicitacao) {
        this.dataInicioLicitacao = dataInicioLicitacao;
    }
    public Date getDataFimLicitacao() {
        return this.dataFimLicitacao;
    }
    
    public void setDataFimLicitacao(Date dataFimLicitacao) {
        this.dataFimLicitacao = dataFimLicitacao;
    }
    public Byte getPontuacao() {
        return this.pontuacao;
    }
    
    public void setPontuacao(Byte pontuacao) {
        this.pontuacao = pontuacao;
    }
    public Byte getPontuacaoComite() {
        return this.pontuacaoComite;
    }
    
    public void setPontuacaoComite(Byte pontuacaoComite) {
        this.pontuacaoComite = pontuacaoComite;
    }
    public Set<Artigorevisao> getArtigorevisaos() {
        return this.artigorevisaos;
    }
    
    public void setArtigorevisaos(Set<Artigorevisao> artigorevisaos) {
        this.artigorevisaos = artigorevisaos;
    }
    public Set<Conferenciacomiteartigoforum> getConferenciacomiteartigoforums() {
        return this.conferenciacomiteartigoforums;
    }
    
    public void setConferenciacomiteartigoforums(Set<Conferenciacomiteartigoforum> conferenciacomiteartigoforums) {
        this.conferenciacomiteartigoforums = conferenciacomiteartigoforums;
    }




}


