package HibernatePackage;
// Generated 16/Abr/2014 23:30:37 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Conferencia generated by hbm2java
 */
public class Conferencia  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Conferenciaedicao> conferenciaedicaos = new HashSet<Conferenciaedicao>(0);

    public Conferencia() {
    }

	
    public Conferencia(String nome) {
        this.nome = nome;
    }
    public Conferencia(String nome, Set<Conferenciaedicao> conferenciaedicaos) {
       this.nome = nome;
       this.conferenciaedicaos = conferenciaedicaos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Conferenciaedicao> getConferenciaedicaos() {
        return this.conferenciaedicaos;
    }
    
    public void setConferenciaedicaos(Set<Conferenciaedicao> conferenciaedicaos) {
        this.conferenciaedicaos = conferenciaedicaos;
    }




}


