package HibernatePackage;
// Generated 28/Jun/2014 14:50:24 by Hibernate Tools 3.6.0



/**
 * ArtigoautoresId generated by hbm2java
 */
public class ArtigoautoresId  implements java.io.Serializable {


     private int idArtigo;
     private int idInvestigador;

    public ArtigoautoresId() {
    }

    public ArtigoautoresId(int idArtigo, int idInvestigador) {
       this.idArtigo = idArtigo;
       this.idInvestigador = idInvestigador;
    }
   
    public int getIdArtigo() {
        return this.idArtigo;
    }
    
    public void setIdArtigo(int idArtigo) {
        this.idArtigo = idArtigo;
    }
    public int getIdInvestigador() {
        return this.idInvestigador;
    }
    
    public void setIdInvestigador(int idInvestigador) {
        this.idInvestigador = idInvestigador;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArtigoautoresId) ) return false;
		 ArtigoautoresId castOther = ( ArtigoautoresId ) other; 
         
		 return (this.getIdArtigo()==castOther.getIdArtigo())
 && (this.getIdInvestigador()==castOther.getIdInvestigador());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdArtigo();
         result = 37 * result + this.getIdInvestigador();
         return result;
   }   


}


