package HibernatePackage;
// Generated 12/Jun/2014 22:28:48 by Hibernate Tools 3.6.0



/**
 * Artigorevisaoitems generated by hbm2java
 */
public class Artigorevisaoitems  implements java.io.Serializable {


     private ArtigorevisaoitemsId id;
     private Artigorevisao artigorevisao;
     private Itemrevisao itemrevisao;
     private Byte classificacao;
     private String descricao;

    public Artigorevisaoitems() {
    }

	
    public Artigorevisaoitems(ArtigorevisaoitemsId id, Artigorevisao artigorevisao, Itemrevisao itemrevisao) {
        this.id = id;
        this.artigorevisao = artigorevisao;
        this.itemrevisao = itemrevisao;
    }
    public Artigorevisaoitems(ArtigorevisaoitemsId id, Artigorevisao artigorevisao, Itemrevisao itemrevisao, Byte classificacao, String descricao) {
       this.id = id;
       this.artigorevisao = artigorevisao;
       this.itemrevisao = itemrevisao;
       this.classificacao = classificacao;
       this.descricao = descricao;
    }
   
    public ArtigorevisaoitemsId getId() {
        return this.id;
    }
    
    public void setId(ArtigorevisaoitemsId id) {
        this.id = id;
    }
    public Artigorevisao getArtigorevisao() {
        return this.artigorevisao;
    }
    
    public void setArtigorevisao(Artigorevisao artigorevisao) {
        this.artigorevisao = artigorevisao;
    }
    public Itemrevisao getItemrevisao() {
        return this.itemrevisao;
    }
    
    public void setItemrevisao(Itemrevisao itemrevisao) {
        this.itemrevisao = itemrevisao;
    }
    public Byte getClassificacao() {
        return this.classificacao;
    }
    
    public void setClassificacao(Byte classificacao) {
        this.classificacao = classificacao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


