package HibernatePackage;
// Generated 12/Jun/2014 22:28:48 by Hibernate Tools 3.6.0



/**
 * ArtigorevisaoitemsId generated by hbm2java
 */
public class ArtigorevisaoitemsId  implements java.io.Serializable {


     private int idArtigoRevisao;
     private int idItemRevisao;

    public ArtigorevisaoitemsId() {
    }

    public ArtigorevisaoitemsId(int idArtigoRevisao, int idItemRevisao) {
       this.idArtigoRevisao = idArtigoRevisao;
       this.idItemRevisao = idItemRevisao;
    }
   
    public int getIdArtigoRevisao() {
        return this.idArtigoRevisao;
    }
    
    public void setIdArtigoRevisao(int idArtigoRevisao) {
        this.idArtigoRevisao = idArtigoRevisao;
    }
    public int getIdItemRevisao() {
        return this.idItemRevisao;
    }
    
    public void setIdItemRevisao(int idItemRevisao) {
        this.idItemRevisao = idItemRevisao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArtigorevisaoitemsId) ) return false;
		 ArtigorevisaoitemsId castOther = ( ArtigorevisaoitemsId ) other; 
         
		 return (this.getIdArtigoRevisao()==castOther.getIdArtigoRevisao())
 && (this.getIdItemRevisao()==castOther.getIdItemRevisao());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdArtigoRevisao();
         result = 37 * result + this.getIdItemRevisao();
         return result;
   }   


}


