package HibernatePackage;
// Generated 27/Jul/2014 19:30:51 by Hibernate Tools 3.6.0



/**
 * Conferenciaartigo generated by hbm2java
 */
public class Conferenciaartigo  implements java.io.Serializable {


     private Integer id;
     private Conferenciaedicao conferenciaedicao;
     private Artigo artigo;
     private Boolean publicar;

    public Conferenciaartigo() {
    }

	
    public Conferenciaartigo(Conferenciaedicao conferenciaedicao, Artigo artigo) {
        this.conferenciaedicao = conferenciaedicao;
        this.artigo = artigo;
    }
    public Conferenciaartigo(Conferenciaedicao conferenciaedicao, Artigo artigo, Boolean publicar) {
       this.conferenciaedicao = conferenciaedicao;
       this.artigo = artigo;
       this.publicar = publicar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conferenciaedicao getConferenciaedicao() {
        return this.conferenciaedicao;
    }
    
    public void setConferenciaedicao(Conferenciaedicao conferenciaedicao) {
        this.conferenciaedicao = conferenciaedicao;
    }
    public Artigo getArtigo() {
        return this.artigo;
    }
    
    public void setArtigo(Artigo artigo) {
        this.artigo = artigo;
    }
    public Boolean getPublicar() {
        return this.publicar;
    }
    
    public void setPublicar(Boolean publicar) {
        this.publicar = publicar;
    }




}


