package HibernatePackage;
// Generated 22/Jul/2014 22:40:36 by Hibernate Tools 3.6.0



/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private Integer id;
     private Investigador investigadorByInvestigadorContactId;
     private Investigador investigadorByIdInvestigador;
     private int idContacto;

    public Contacto() {
    }

    public Contacto(Investigador investigadorByInvestigadorContactId, Investigador investigadorByIdInvestigador, int idContacto) {
       this.investigadorByInvestigadorContactId = investigadorByInvestigadorContactId;
       this.investigadorByIdInvestigador = investigadorByIdInvestigador;
       this.idContacto = idContacto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Investigador getInvestigadorByInvestigadorContactId() {
        return this.investigadorByInvestigadorContactId;
    }
    
    public void setInvestigadorByInvestigadorContactId(Investigador investigadorByInvestigadorContactId) {
        this.investigadorByInvestigadorContactId = investigadorByInvestigadorContactId;
    }
    public Investigador getInvestigadorByIdInvestigador() {
        return this.investigadorByIdInvestigador;
    }
    
    public void setInvestigadorByIdInvestigador(Investigador investigadorByIdInvestigador) {
        this.investigadorByIdInvestigador = investigadorByIdInvestigador;
    }
    public int getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(int idContacto) {
        this.idContacto = idContacto;
    }




}


