package HibernatePackage;
// Generated 28/Jun/2014 15:34:25 by Hibernate Tools 3.6.0



/**
 * Investigadorareaconhecimento generated by hbm2java
 */
public class Investigadorareaconhecimento  implements java.io.Serializable {


     private Integer id;
     private Subtema subtema;
     private Investigador investigador;
     private Byte grauConfianca;
     private Byte preferencia;

    public Investigadorareaconhecimento() {
    }

	
    public Investigadorareaconhecimento(Subtema subtema, Investigador investigador) {
        this.subtema = subtema;
        this.investigador = investigador;
    }
    public Investigadorareaconhecimento(Subtema subtema, Investigador investigador, Byte grauConfianca, Byte preferencia) {
       this.subtema = subtema;
       this.investigador = investigador;
       this.grauConfianca = grauConfianca;
       this.preferencia = preferencia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Subtema getSubtema() {
        return this.subtema;
    }
    
    public void setSubtema(Subtema subtema) {
        this.subtema = subtema;
    }
    public Investigador getInvestigador() {
        return this.investigador;
    }
    
    public void setInvestigador(Investigador investigador) {
        this.investigador = investigador;
    }
    public Byte getGrauConfianca() {
        return this.grauConfianca;
    }
    
    public void setGrauConfianca(Byte grauConfianca) {
        this.grauConfianca = grauConfianca;
    }
    public Byte getPreferencia() {
        return this.preferencia;
    }
    
    public void setPreferencia(Byte preferencia) {
        this.preferencia = preferencia;
    }




}


