package HibernatePackage;
// Generated 27/Jul/2014 15:52:48 by Hibernate Tools 3.6.0



/**
 * Artigopalavrachave generated by hbm2java
 */
public class Artigopalavrachave  implements java.io.Serializable {


     private Integer id;
     private Artigo artigo;
     private String palavraChave;

    public Artigopalavrachave() {
    }

	
    public Artigopalavrachave(Artigo artigo) {
        this.artigo = artigo;
    }
    public Artigopalavrachave(Artigo artigo, String palavraChave) {
       this.artigo = artigo;
       this.palavraChave = palavraChave;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Artigo getArtigo() {
        return this.artigo;
    }
    
    public void setArtigo(Artigo artigo) {
        this.artigo = artigo;
    }
    public String getPalavraChave() {
        return this.palavraChave;
    }
    
    public void setPalavraChave(String palavraChave) {
        this.palavraChave = palavraChave;
    }




}


