package HibernatePackage;
// Generated 27/Jul/2014 15:52:48 by Hibernate Tools 3.6.0



/**
 * Artigoinvestigador generated by hbm2java
 */
public class Artigoinvestigador  implements java.io.Serializable {


     private Integer id;
     private Artigo artigo;
     private Investigador investigador;

    public Artigoinvestigador() {
    }

    public Artigoinvestigador(Artigo artigo, Investigador investigador) {
       this.artigo = artigo;
       this.investigador = investigador;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Artigo getArtigo() {
        return this.artigo;
    }
    
    public void setArtigo(Artigo artigo) {
        this.artigo = artigo;
    }
    public Investigador getInvestigador() {
        return this.investigador;
    }
    
    public void setInvestigador(Investigador investigador) {
        this.investigador = investigador;
    }




}


