package HibernatePackage;
// Generated 27/Jul/2014 19:30:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Conferenciacomiteartigoforummensagem generated by hbm2java
 */
public class Conferenciacomiteartigoforummensagem  implements java.io.Serializable {


     private Integer id;
     private Conferenciacomiteartigoforum conferenciacomiteartigoforum;
     private Investigador investigador;
     private Date data;
     private String mensagem;

    public Conferenciacomiteartigoforummensagem() {
    }

	
    public Conferenciacomiteartigoforummensagem(Conferenciacomiteartigoforum conferenciacomiteartigoforum, Investigador investigador) {
        this.conferenciacomiteartigoforum = conferenciacomiteartigoforum;
        this.investigador = investigador;
    }
    public Conferenciacomiteartigoforummensagem(Conferenciacomiteartigoforum conferenciacomiteartigoforum, Investigador investigador, Date data, String mensagem) {
       this.conferenciacomiteartigoforum = conferenciacomiteartigoforum;
       this.investigador = investigador;
       this.data = data;
       this.mensagem = mensagem;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conferenciacomiteartigoforum getConferenciacomiteartigoforum() {
        return this.conferenciacomiteartigoforum;
    }
    
    public void setConferenciacomiteartigoforum(Conferenciacomiteartigoforum conferenciacomiteartigoforum) {
        this.conferenciacomiteartigoforum = conferenciacomiteartigoforum;
    }
    public Investigador getInvestigador() {
        return this.investigador;
    }
    
    public void setInvestigador(Investigador investigador) {
        this.investigador = investigador;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }




}


